---
- name: Install python3, docker, docker-compose
  hosts: tag_Name_dev_server
  become: true
  become_user: root
  gather_facts: False
  tasks:
    - name: Install Python3
      vars:
        ansible_python_interpreter: /usr/bin/python
      yum:
        name:
          - python3
          - docker
        update_cache: true
        state: present
    - name: Install Docker-Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.27.4/docker-compose-Linux-{{lookup('pipe', 'uname -m')}}
        dest: /usr/local/bin/docker-compose
        mode: +x
    - name: Start docker daemon
      systemd:
        name: docker
        state: started
    - name: Add ec2 User to docker Group
      user:
        name: ec2-user
        groups: docker
        append: true
    - name: Reconnect to server session
      meta: reset_connection
    - name: Install docker-py
      pip:
        name:
          - docker
          - docker-compose
        state: present